language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="fae7c6c3-51bc-46ba-9ba3-12ea608f657b"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - kirshaav@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
